FROM python:3.11-slim

RUN apt update && \
    apt install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /repo

ENV POETRY_VER="1.8.3" \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=0 \
    POETRY_VIRTUALENVS_CREATE=False \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN pip install poetry==$POETRY_VER

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

COPY . .

ENV DEADLOCK_DIR="/data" \
    WORK_DIR="/work" \
    OUTPUT_DIR="/output"

ENTRYPOINT [ "python3", "src/deadbot.py", "--import_files", "--decompile", "--parse", "--english-only" ]
